# Generated by Django 2.2.7 on 2020-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option1_count', models.PositiveIntegerField(default=0)),
                ('option2_count', models.PositiveIntegerField(default=0)),
                ('option3_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Poll',
                'ordering': ['-id'],
            },
        ),
    ]
